apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://174.37.17.188:8001
  name: optumera
contexts:
- context:
    cluster: optumera
    namespace: user5
    user: user5
  name: optumera-context
current-context: optumera-context
kind: Config
preferences: {}
users:
- name: optumera-user
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiNjc5NDhlZThkZDNmYjM4Mjg4MGJmZjk4NjJlODA5NzJiYTJiZjk5YSIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoidXNlcjUiLCJpc3MiOiJodHRwczovL29wdHVtZXJhLmljcDo5NDQzL29pZGMvZW5kcG9pbnQvT1AiLCJhdWQiOiI2MTkxMTQ4YjE2ZDdhNWI1MTRjNzQyMGE2NGE2NmZkNSIsImV4cCI6MTU2MDc4ODM1NCwiaWF0IjoxNTYwNzU5NTU0LCJzdWIiOiJ1c2VyNSIsInRlYW1Sb2xlTWFwcGluZ3MiOlsic3lzdGVtOm1hc3RlcnMiXX0.Al4xQ9iaj2_SxBXLxoO0KQGQzT44lI__powdXfIoq920mRMPt8v5pwliJnGallUYOfttiX9yP-aQIrtyJ_ZYR5SNvwarW3o4qtAiM78dCcmmLkw78u1dow_Wpi4i8as-6LKDRSrPMY8VxL_CPA8pdBiRHZTLqgP2bCOxCCXXUJnPb9QpsaU-mpmv8nqbRVXv7aVvPwcF73TKr9_HHmZg4Lh-XqWhxiZIlJyh03acq8KGkjBrPe-Tahpy9diqrTVXhSB1ZQ9GlxnhjG94Fd0MEHSmBoB9QO_Y7ZwpSf8AcsaATOBZdr7UlTw077UdyhsP1doZikeoHPvUeTgHYiRo5A
- name: user5
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiNmNkZTQwM2I3YmEyYWIxNmU4OGFlZjUwN2NmYWU4YzMwNGQxMzg5MCIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoidXNlcjUiLCJpc3MiOiJodHRwczovL29wdHVtZXJhLmljcDo5NDQzL29pZGMvZW5kcG9pbnQvT1AiLCJhdWQiOiI2MTkxMTQ4YjE2ZDdhNWI1MTRjNzQyMGE2NGE2NmZkNSIsImV4cCI6MTU2MDg4NTI1MiwiaWF0IjoxNTYwODU2NDUyLCJzdWIiOiJ1c2VyNSIsInRlYW1Sb2xlTWFwcGluZ3MiOlsic3lzdGVtOm1hc3RlcnMiXX0.lvhVA3xwbLLJH8g0mxWavdUiwRKE3E0df5c0LK4S0zDy9kL5DzMtX_to9XhNMJ5-Si7Lvvd1iDDZLfVoTOwWcaOFufIHfxdr9qbYwr4WuD7g2xDPXFiiMRMwsdwchZqnonZZxTA0CGyrCfD2FeHqVc_DpT5vdIYSxgV2hHnd8AG_2g9Wu1mygOscddHlCrxe6-YRrwqHajXgo7X22eQV9aMmRyDjwBERsoUHtelelKO55SSesoIIn60r-7iTXKuIH-jMvwv9sl8ZgTGcjQvUqleeV5UyXvSia2eG1JVif62o12vC9pz4SoTLFTQ5LBsS_60CixhTjQYP1RYSdShPIg
